apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hazelcast
spec:
  replicas: 3
  serviceName: hazelcast
  selector:
    matchLabels:
      app: hazelcast
  template:
    metadata:
      labels:
        app: hazelcast
    spec:
      containers:
        - name: hazelcast
          image: hazelcast/hazelcast-enterprise:4.0
          imagePullPolicy: Always
          ports:
          - containerPort: 5701
          env:
          - name: HZ_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                name: hz-license-key
                key: license
          - name: KEYSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keystore
                key: keystorePassword
          - name: TRUSTSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keystore
                key: truststorePassword
          - name: JAVA_OPTS
            value: "-Dhazelcast.config=/data/hazelcast/configuration/hazelcast.yaml -Djavax.net.ssl.keyStore=/data/hazelcast/secrets/keystore -Djavax.net.ssl.keyStorePassword=${KEYSTORE_PASSWORD} -Djavax.net.ssl.trustStore=/data/hazelcast/secrets/truststore -Djavax.net.ssl.trustStorePassword=${TRUSTSTORE_PASSWORD}"
          volumeMounts:
          - name: hazelcast-configuration
            mountPath: /data/hazelcast/configuration
          - name: hazelcast-secrets
            mountPath: /data/hazelcast/secrets
      volumes:
      - name: hazelcast-configuration
        configMap:
          name: hazelcast-configuration
      - name: hazelcast-secrets
        secret:
          secretName: keystore
